// config/forms.js
// Comprehensive form definitions for Olive Place facility

export const formCategories = {
  admission: "Admission & Assessment",
  consent: "Consent & Authorization",
  medical: "Medical & Health",
  employment: "Employment & Staff",
  policies: "Policies & Procedures",
  administrative: "Administrative",
};

export const forms = [
  // ADMISSION & ASSESSMENT
  {
    id: "complete-admission",
    name: "Complete Admission Paperwork",
    category: "admission",
    description: "Comprehensive admission documentation",
    fileReference: "Blank Complete Admission Paperwork on lh.pdf",
    fields: [
      { name: "firstName", label: "First Name", type: "text", required: true },
      { name: "lastName", label: "Last Name", type: "text", required: true },
      { name: "dateOfBirth", label: "Date of Birth", type: "date", required: true },
      { name: "socialSecurity", label: "Social Security Number", type: "text", required: false },
      { name: "address", label: "Address", type: "text", required: true },
      { name: "city", label: "City", type: "text", required: true },
      { name: "state", label: "State", type: "text", required: true },
      { name: "zipCode", label: "ZIP Code", type: "text", required: true },
      { name: "phone", label: "Phone Number", type: "tel", required: true },
      { name: "email", label: "Email Address", type: "email", required: false },
      { name: "admissionDate", label: "Admission Date", type: "date", required: true },
      { name: "emergencyContact", label: "Emergency Contact Name", type: "text", required: true },
      { name: "emergencyPhone", label: "Emergency Contact Phone", type: "tel", required: true },
      { name: "notes", label: "Additional Notes", type: "textarea", required: false },
    ],
  },
  {
    id: "initial-assessment",
    name: "Initial Assessment",
    category: "admission",
    description: "Initial clinical assessment",
    fileReference: "Initial Assessment Blank on lh.pdf",
    fields: [
      { name: "clientName", label: "Client Name", type: "text", required: true },
      { name: "assessmentDate", label: "Assessment Date", type: "date", required: true },
      { name: "assessedBy", label: "Assessed By", type: "text", required: true },
      { name: "medicalHistory", label: "Medical History", type: "textarea", required: false },
      { name: "currentMedications", label: "Current Medications", type: "textarea", required: false },
      { name: "allergies", label: "Allergies", type: "textarea", required: false },
      { name: "functionalStatus", label: "Functional Status", type: "textarea", required: false },
      { name: "mentalHealthHistory", label: "Mental Health History", type: "textarea", required: false },
      { name: "substanceUseHistory", label: "Substance Use History", type: "textarea", required: false },
      { name: "supportSystem", label: "Support System", type: "textarea", required: false },
    ],
  },
  {
    id: "face-sheet",
    name: "Face Sheet",
    category: "admission",
    description: "Client demographic and administrative information",
    fileReference: "Face Sheet Blank on lh.pdf",
    fields: [
      { name: "clientId", label: "Client ID", type: "text", required: true },
      { name: "clientName", label: "Client Name", type: "text", required: true },
      { name: "dateOfBirth", label: "Date of Birth", type: "date", required: true },
      { name: "age", label: "Age", type: "number", required: false },
      { name: "gender", label: "Gender", type: "select", options: ["Male", "Female", "Non-binary", "Prefer not to say"], required: false },
      { name: "race", label: "Race/Ethnicity", type: "text", required: false },
      { name: "language", label: "Primary Language", type: "text", required: false },
      { name: "maritalStatus", label: "Marital Status", type: "select", options: ["Single", "Married", "Divorced", "Widowed"], required: false },
      { name: "insuranceProvider", label: "Insurance Provider", type: "text", required: false },
      { name: "insurancePolicyNumber", label: "Policy Number", type: "text", required: false },
      { name: "referralSource", label: "Referral Source", type: "text", required: false },
    ],
  },

  // CONSENT & AUTHORIZATION
  {
    id: "consent-to-treat",
    name: "Consent to Treat",
    category: "consent",
    description: "Treatment authorization and acknowledgment",
    fileReference: "Olive Place Consent to Treat on lh.pdf",
    fields: [
      { name: "clientName", label: "Client Name", type: "text", required: true },
      { name: "guardianName", label: "Guardian/Representative Name", type: "text", required: false },
      { name: "treatmentDescription", label: "Treatment Description", type: "textarea", required: true },
      { name: "risks", label: "Understood Risks", type: "textarea", required: false },
      { name: "benefits", label: "Understood Benefits", type: "textarea", required: false },
      { name: "clientSignatureDate", label: "Client Signature Date", type: "date", required: true },
      { name: "witnessName", label: "Witness Name", type: "text", required: false },
      { name: "witnessDate", label: "Witness Date", type: "date", required: false },
    ],
  },
  {
    id: "consent-exchange-info",
    name: "Consent to Exchange Information",
    category: "consent",
    description: "Authorization to share client information",
    fileReference: "Olive Place Consent to Exchange Info on lh.pdf",
    fields: [
      { name: "clientName", label: "Client Name", type: "text", required: true },
      { name: "informationTypes", label: "Types of Information to Share", type: "textarea", required: true },
      { name: "recipients", label: "Recipients of Information", type: "textarea", required: true },
      { name: "purpose", label: "Purpose of Information Sharing", type: "textarea", required: true },
      { name: "expirationDate", label: "Consent Expiration Date", type: "date", required: false },
      { name: "clientSignatureDate", label: "Client Signature Date", type: "date", required: true },
      { name: "revokedDate", label: "Date Revoked (if applicable)", type: "date", required: false },
    ],
  },
  {
    id: "consent-psychotropic",
    name: "Consent for Psychotropic Drugs",
    category: "consent",
    description: "Informed consent for psychotropic medication",
    fileReference: "Blank Olive Place Consent Pyscotropic Drugs on lh.pdf",
    fields: [
      { name: "clientName", label: "Client Name", type: "text", required: true },
      { name: "prescriber", label: "Prescriber Name", type: "text", required: true },
      { name: "medicationName", label: "Medication Name", type: "text", required: true },
      { name: "dosage", label: "Dosage", type: "text", required: true },
      { name: "frequency", label: "Frequency", type: "text", required: true },
      { name: "sideEffects", label: "Potential Side Effects Discussed", type: "textarea", required: true },
      { name: "alternatives", label: "Alternative Treatments Discussed", type: "textarea", required: false },
      { name: "risks", label: "Risks Explained", type: "textarea", required: true },
      { name: "clientSignatureDate", label: "Client Signature Date", type: "date", required: true },
    ],
  },
  {
    id: "photo-consent",
    name: "Photography Release Form",
    category: "consent",
    description: "Consent for photography and media use",
    fileReference: "Olive Place Photography Release Form on lh.pdf",
    fields: [
      { name: "clientName", label: "Client Name", type: "text", required: true },
      { name: "photoType", label: "Type of Photography Consented", type: "textarea", required: true },
      { name: "mediaUse", label: "Approved Media Use", type: "textarea", required: true },
      { name: "duration", label: "Duration of Consent", type: "text", required: false },
      { name: "compensation", label: "Compensation Offered", type: "text", required: false },
      { name: "clientSignatureDate", label: "Client Signature Date", type: "date", required: true },
      { name: "withdrawn", label: "Consent Withdrawn (if applicable)", type: "date", required: false },
    ],
  },

  // MEDICAL & HEALTH
  {
    id: "medical-history",
    name: "Medical History Form",
    category: "medical",
    description: "Comprehensive medical history",
    fileReference: "Medical History Form Blank on lh.pdf",
    fields: [
      { name: "clientName", label: "Client Name", type: "text", required: true },
      { name: "dateOfBirth", label: "Date of Birth", type: "date", required: true },
      { name: "primaryCarePhysician", label: "Primary Care Physician", type: "text", required: false },
      { name: "chronicConditions", label: "Chronic Conditions", type: "textarea", required: false },
      { name: "surgeries", label: "Previous Surgeries", type: "textarea", required: false },
      { name: "hospitalizations", label: "Hospitalizations", type: "textarea", required: false },
      { name: "medications", label: "Current Medications", type: "textarea", required: false },
      { name: "allergies", label: "Allergies & Reactions", type: "textarea", required: true },
      { name: "familyHistory", label: "Family Medical History", type: "textarea", required: false },
      { name: "vaccinations", label: "Vaccination Status", type: "textarea", required: false },
      { name: "lastPhysical", label: "Date of Last Physical Exam", type: "date", required: false },
    ],
  },
  {
    id: "activity-charting",
    name: "Activity Charting",
    category: "medical",
    description: "Daily activity and behavior documentation",
    fileReference: "Blank Activity Charting on lh.pdf",
    fields: [
      { name: "clientName", label: "Client Name", type: "text", required: true },
      { name: "chartingDate", label: "Charting Date", type: "date", required: true },
      { name: "chartedBy", label: "Charted By", type: "text", required: true },
      { name: "timeOfObservation", label: "Time of Observation", type: "time", required: true },
      { name: "activities", label: "Activities Performed", type: "textarea", required: true },
      { name: "mood", label: "Mood/Affect", type: "text", required: false },
      { name: "behavior", label: "Behavior Observations", type: "textarea", required: false },
      { name: "socialInteraction", label: "Social Interaction", type: "textarea", required: false },
      { name: "incidents", label: "Any Incidents or Concerns", type: "textarea", required: false },
      { name: "interventions", label: "Interventions Provided", type: "textarea", required: false },
    ],
  },

  // EMPLOYMENT & STAFF
  {
    id: "employment-verification",
    name: "Employment Verification Form",
    category: "employment",
    description: "Employment history and verification",
    fileReference: "Olive Place Employment Verification Form on lh.pdf",
    fields: [
      { name: "employeeName", label: "Employee Name", type: "text", required: true },
      { name: "employeeId", label: "Employee ID", type: "text", required: true },
      { name: "position", label: "Position", type: "text", required: true },
      { name: "department", label: "Department", type: "text", required: true },
      { name: "startDate", label: "Start Date", type: "date", required: true },
      { name: "endDate", label: "End Date (if applicable)", type: "date", required: false },
      { name: "status", label: "Employment Status", type: "select", options: ["Full-time", "Part-time", "Contract", "Terminated"], required: true },
      { name: "salary", label: "Salary Range (Optional)", type: "text", required: false },
      { name: "supervisor", label: "Current/Former Supervisor", type: "text", required: true },
      { name: "verificationDate", label: "Verification Date", type: "date", required: true },
      { name: "verifiedBy", label: "Verified By", type: "text", required: true },
    ],
  },
  {
    id: "job-description-dsp",
    name: "Job Description - DSP",
    category: "employment",
    description: "Direct Support Professional job description",
    fileReference: "Job Description DSP Blank on lh.pdf",
    fields: [
      { name: "position", label: "Position Title", type: "text", required: true },
      { name: "reportingTo", label: "Reports To", type: "text", required: true },
      { name: "department", label: "Department", type: "text", required: true },
      { name: "jobSummary", label: "Job Summary", type: "textarea", required: true },
      { name: "duties", label: "Primary Duties and Responsibilities", type: "textarea", required: true },
      { name: "requirements", label: "Required Qualifications", type: "textarea", required: true },
      { name: "desiredQualifications", label: "Desired Qualifications", type: "textarea", required: false },
      { name: "physicalRequirements", label: "Physical Requirements", type: "textarea", required: false },
      { name: "workEnvironment", label: "Work Environment", type: "textarea", required: false },
      { name: "approvedDate", label: "Date Approved", type: "date", required: true },
    ],
  },
  {
    id: "staff-entry-log",
    name: "Staff Entry Log",
    category: "employment",
    description: "Daily staff entry documentation",
    fileReference: "Blank Staff Entry Log.docx",
    fields: [
      { name: "date", label: "Date", type: "date", required: true },
      { name: "staffName", label: "Staff Member Name", type: "text", required: true },
      { name: "staffId", label: "Staff ID", type: "text", required: true },
      { name: "position", label: "Position", type: "text", required: true },
      { name: "entryTime", label: "Entry Time", type: "time", required: true },
      { name: "exitTime", label: "Exit Time", type: "time", required: false },
      { name: "area", label: "Area/Department", type: "text", required: true },
      { name: "purpose", label: "Purpose", type: "text", required: false },
      { name: "notes", label: "Notes", type: "textarea", required: false },
    ],
  },
  {
    id: "employee-schedule",
    name: "Employee Schedule",
    category: "employment",
    description: "Staff scheduling and availability",
    fileReference: "Employee Schedule on lh.pdf",
    fields: [
      { name: "scheduleMonth", label: "Schedule Month/Year", type: "text", required: true },
      { name: "departmentHead", label: "Department Head", type: "text", required: true },
      { name: "approvalDate", label: "Approval Date", type: "date", required: true },
      { name: "notes", label: "Schedule Notes", type: "textarea", required: false },
    ],
  },

  // POLICIES & PROCEDURES
  {
    id: "grievance-policy",
    name: "Grievance Policy",
    category: "policies",
    description: "Grievance reporting and resolution procedures",
    fileReference: "Olive Place grivance policy on lh.pdf",
    fields: [
      { name: "grievantName", label: "Grievant Name", type: "text", required: true },
      { name: "grievantRole", label: "Grievant Role", type: "text", required: true },
      { name: "dateSubmitted", label: "Date Submitted", type: "date", required: true },
      { name: "grievanceDescription", label: "Grievance Description", type: "textarea", required: true },
      { name: "respondent", label: "Respondent Name", type: "text", required: false },
      { name: "reliefSought", label: "Relief Sought", type: "textarea", required: false },
      { name: "dateFiled", label: "Formal Filing Date", type: "date", required: true },
      { name: "status", label: "Status", type: "select", options: ["Pending", "Under Review", "Resolved", "Appealed"], required: true },
      { name: "resolutionDate", label: "Resolution Date", type: "date", required: false },
    ],
  },
  {
    id: "fire-safety",
    name: "Fire Safety",
    category: "policies",
    description: "Fire safety procedures and training",
    fileReference: "Olive Place Fire Safety on lh.pdf",
    fields: [
      { name: "trainingDate", label: "Training Date", type: "date", required: true },
      { name: "trainingType", label: "Training Type", type: "select", options: ["Initial", "Annual Review", "Refresher"], required: true },
      { name: "participantName", label: "Participant Name", type: "text", required: true },
      { name: "trainerName", label: "Trainer Name", type: "text", required: true },
      { name: "topicsCovered", label: "Topics Covered", type: "textarea", required: true },
      { name: "evacuationRoute", label: "Evacuation Routes Reviewed", type: "text", required: false },
      { name: "extinguisherTraining", label: "Fire Extinguisher Training", type: "text", required: false },
      { name: "signatureDate", label: "Signature Date", type: "date", required: true },
    ],
  },
  {
    id: "confidential-practices",
    name: "Confidential Practices",
    category: "policies",
    description: "Confidentiality and privacy policies",
    fileReference: "confidential practices.docx",
    fields: [
      { name: "employeeName", label: "Employee Name", type: "text", required: true },
      { name: "position", label: "Position", type: "text", required: true },
      { name: "acknowledgeConfidentiality", label: "Acknowledge Understanding of Confidentiality", type: "checkbox", required: true },
      { name: "privacyCompliance", label: "Privacy Compliance Agreement", type: "checkbox", required: true },
      { name: "dataProtection", label: "Data Protection Commitment", type: "checkbox", required: true },
      { name: "signatureDate", label: "Signature Date", type: "date", required: true },
      { name: "notes", label: "Additional Notes", type: "textarea", required: false },
    ],
  },

  // ADMINISTRATIVE
  {
    id: "acknowledgement",
    name: "Acknowledgement",
    category: "administrative",
    description: "Receipt and acknowledgment of documents",
    fileReference: "Blank Acknowledgement on lh.pdf",
    fields: [
      { name: "personName", label: "Person Acknowledging", type: "text", required: true },
      { name: "documentsReceived", label: "Documents Received", type: "textarea", required: true },
      { name: "dateReceived", label: "Date Received", type: "date", required: true },
      { name: "condition", label: "Condition of Documents", type: "text", required: false },
      { name: "signatureDate", label: "Signature Date", type: "date", required: true },
      { name: "witnessName", label: "Witness Name", type: "text", required: false },
    ],
  },
  {
    id: "ar-form",
    name: "AR Form",
    category: "administrative",
    description: "Administrative record form",
    fileReference: "Blank AR form on lh.pdf",
    fields: [
      { name: "recordNumber", label: "Record Number", type: "text", required: true },
      { name: "dateCreated", label: "Date Created", type: "date", required: true },
      { name: "createdBy", label: "Created By", type: "text", required: true },
      { name: "recordType", label: "Record Type", type: "text", required: true },
      { name: "subject", label: "Subject", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "retention", label: "Retention Schedule", type: "text", required: false },
    ],
  },
  {
    id: "individuals-rights",
    name: "Individual's Rights",
    category: "administrative",
    description: "Explanation of client/employee rights",
    fileReference: "Individual's Rights Blank on lh.pdf",
    fields: [
      { name: "personName", label: "Person Name", type: "text", required: true },
      { name: "rightsExplainedDate", label: "Date Rights Explained", type: "date", required: true },
      { name: "explainedBy", label: "Explained By", type: "text", required: true },
      { name: "understandsRights", label: "Acknowledges Understanding of Rights", type: "checkbox", required: true },
      { name: "grievanceRights", label: "Grievance Rights Explained", type: "checkbox", required: true },
      { name: "consentRights", label: "Consent and Refusal Rights Explained", type: "checkbox", required: true },
      { name: "signatureDate", label: "Signature Date", type: "date", required: true },
    ],
  },
  {
    id: "provider-choice",
    name: "Provider Choice",
    category: "administrative",
    description: "Selection of care providers",
    fileReference: "Provider Choice Blank on lh.pdf",
    fields: [
      { name: "clientName", label: "Client Name", type: "text", required: true },
      { name: "clientId", label: "Client ID", type: "text", required: true },
      { name: "selectedProvider", label: "Selected Provider", type: "text", required: true },
      { name: "providerSpecialty", label: "Provider Specialty", type: "text", required: false },
      { name: "dateOfChoice", label: "Date of Choice", type: "date", required: true },
      { name: "reasonForChoice", label: "Reason for Selection", type: "textarea", required: false },
      { name: "alternativeOptions", label: "Alternative Options Presented", type: "textarea", required: false },
      { name: "acknowledgeDate", label: "Client Acknowledgment Date", type: "date", required: true },
    ],
  },
  {
    id: "admission-discharge-protocol",
    name: "Admission-Discharge Protocol",
    category: "administrative",
    description: "Procedures for admission and discharge",
    fileReference: "Olive Place Admission-Discharge Protocol on lh.pdf",
    fields: [
      { name: "clientName", label: "Client Name", type: "text", required: true },
      { name: "admissionDate", label: "Admission Date", type: "date", required: true },
      { name: "expectedDischargeDate", label: "Expected Discharge Date", type: "date", required: false },
      { name: "actualDischargeDate", label: "Actual Discharge Date", type: "date", required: false },
      { name: "reasonForDischarge", label: "Reason for Discharge", type: "text", required: false },
      { name: "discharge Location", label: "Discharge Location", type: "text", required: false },
      { name: "summaryOfServices", label: "Summary of Services Provided", type: "textarea", required: false },
      { name: "clientConditionAtDischarge", label: "Client Condition at Discharge", type: "textarea", required: false },
    ],
  },
  {
    id: "rights-policy",
    name: "Rights Policy",
    category: "administrative",
    description: "Facility rights and responsibilities policies",
    fileReference: "Rights Olive Place on lh.pdf",
    fields: [
      { name: "documentDate", label: "Document Date", type: "date", required: true },
      { name: "effectiveDate", label: "Effective Date", type: "date", required: true },
      { name: "policyAppliedTo", label: "Policy Applied To", type: "textarea", required: true },
      { name: "approvedBy", label: "Approved By", type: "text", required: true },
      { name: "notes", label: "Policy Notes", type: "textarea", required: false },
    ],
  },
];
